---
title: "p8105_hw4_cgd2137"
author: "Carolina Downie"
date: "10/26/2017"
output: html_document
---

#Loading packages
```{r}
library(tidyverse)
library(ggplot2)
```



#Problem 2
 
```{r clean pols data}

#This is based on the answer key for HW2

pols <- read_csv("fivethirtyeight_datasets/pols-month.csv") %>%
  mutate(date = lubridate::floor_date(mon, "month"), 
         president = recode(prez_gop, `0` = "dem", `1` = "gop", `2` = "gop")) %>%
  separate(mon, into = c("year", "month", "day"), convert = TRUE) %>%
  mutate(month = month.name[month]) %>%
  select(year, month, date, president, gov_gop, sen_gop, rep_gop, gov_dem, sen_dem, rep_dem)


#This is what I did in HW2
pols_month <- read_csv("fivethirtyeight_datasets/pols-month.csv", col_names=TRUE) %>%
mutate(president = if_else(prez_dem == "1", "dem", "rep")) %>%
separate(mon, into = c("year", "month", "day"), sep = "-") %>%
mutate(month=as.integer(month)) %>%
mutate(month = month.name[month]) %>%
mutate(month = as.character(month)) %>%
select(-c(prez_dem, prez_gop, day)) %>% 
gather(key="governors", value="num_governors", gov_gop, gov_dem) %>% 
gather(key="senators", value="num_senators", sen_gop, sen_dem) %>% 
gather(key="representatives", value="num_representatives", rep_gop, rep_dem)%>%
separate(governors, into= c("remove1", "governors"), sep ="_") %>%
separate(senators, into= c("remove2", "senators"), sep= "_") %>%
separate(representatives, into = c("remove3", "representatives"), sep = "_") %>%
select(-c( remove1, remove2, remove3))

```


```{r clean GDP data}
GDP <- read_csv("fivethirtyeight_datasets/GDP.csv", col_names = TRUE) %>% 
  rename(date = DATE, GDP_value = VALUE) %>% filter(GDP_value != ".")

```

```{r joining pols and GDP data}

#Only joining where there is data for both pols and GDP
pols_GDP <- inner_join(pols, GDP, by = "date")


```

