---
title: "p8105_hw4_cgd2137"
author: "Carolina Downie"
date: "10/26/2017"
output: html_document
---

#Loading packages
```{r}
library(tidyverse)
library(ggplot2)
```


#Problem 2
```{r clean pols data}

#Note: The way this is tidied is based on the answer key for HW2

pols <- read_csv("./Data/pols-month.csv") %>%
  mutate(date = lubridate::floor_date(mon, "month"), 
         president = recode(prez_gop, `0` = "dem", `1` = "gop", `2` = "gop")) %>%
  separate(mon, into = c("year", "month", "day"), convert = TRUE) %>%
  mutate(month = month.name[month]) %>%
  select(year, month, date, president, gov_gop, sen_gop, rep_gop, gov_dem, sen_dem, rep_dem)

```

```{r clean GDP data}
GDP <- read_csv("./Data/GDP.csv", col_names = TRUE) %>% 
  rename(date = DATE, GDP_value = VALUE) %>% filter(GDP_value != ".")

```

```{r joining pols and GDP data}

#Only joining where there is data for both pols and GDP
pols_GDP <- inner_join(pols, GDP, by = "date")

```

The following chunk creates a plot of GDP value over time, with colored dots representing the party of the president at a given time. The plot also inlcudes a smooth line tracking the mean GPD value over the course of the dates in the data.

```{r gdp_over_time}
pols_GDP %>% 
  mutate(GDP_value = as.numeric(GDP_value)) %>% 
  ggplot(aes(x = date, y = GDP_value)) +
  geom_point(aes(color = president)) +
  geom_smooth(se = FALSE) +
  theme_bw()
```

